### ISSUE TITLE
Can not logging errors via email when message contains UTF-8 characters

### ISSUE THREAD

**Issue by andras-tim** [andras-tim/StoreKeeper#126]
Can not send error message when message part contains UTF-8 characters:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/handlers.py", line 984, in emit
    smtp.sendmail(self.fromaddr, self.toaddrs, msg)
  File "/usr/lib/python3.4/smtplib.py", line 764, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 76: ordinal not in range(128)
Call stack:
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/storekeeper/server/flask/lib/python3.4/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/storekeeper/server/app/views/error.py", line 25, in post
    app.logger.error('client-side error: user: {!r}\n{}'.format(g.user, self._format_data(data)))
```

The `smtplib` calls a bad encoding in **/usr/lib/python3.4/smtplib.py@764**:

```
def sendmail(...):
    ...
    if isinstance(msg, str):
        msg = _fix_eols(msg).encode('ascii')
    ...
```

**Comment by andras-tim** [comment]
https://bugs.python.org/issue9208#msg252931

> In 3.4/3.5 a better fix would be to use `EmailMessage` instead of `Message`, and `smtp.send_message` instead of`smtp.sendmail`.  That will do the right thing, where "the right thing" is defined as defaulting to utf-8 for both headers and body.  A specific application might want other defaults, in which case one should proceed as Vinay suggests.
> 
> You could open a new issue requesting the use of `EmailMessage`/`send_message` in python3 logging if you want to pursue this.  Note that this would also allow unicode in the display name part of the addresses.
