### ISSUE TITLE
Can not read config.yml when it contains UTF-8 characters

### ISSUE THREAD

**Issue by andras-tim** [andras-tim/StoreKeeper#78]

**Comment by andras-tim** [comment]
The exception:

```
Sun Oct  4 09:37:53 2015 - *** Starting uWSGI 1.9.17.1-debian (64bit) on [Sun Oct  4 09:37:53 2015] ***
Sun Oct  4 09:37:53 2015 - compiled with version: 4.8.2 on 23 March 2014 17:15:32
Sun Oct  4 09:37:53 2015 - os: Linux-3.2.0-80-generic #116-Ubuntu SMP Mon Mar 23 17:11:03 UTC 2015
Sun Oct  4 09:37:53 2015 - nodename: server
Sun Oct  4 09:37:53 2015 - machine: x86_64
Sun Oct  4 09:37:53 2015 - clock source: unix
Sun Oct  4 09:37:53 2015 - pcre jit disabled
Sun Oct  4 09:37:53 2015 - detected number of CPU cores: 2
Sun Oct  4 09:37:53 2015 - current working directory: /
Sun Oct  4 09:37:53 2015 - writing pidfile to /run/uwsgi/app/storekeeper/pid
Sun Oct  4 09:37:53 2015 - detected binary path: /usr/bin/uwsgi-core
Sun Oct  4 09:37:53 2015 - setgid() to 106
Sun Oct  4 09:37:53 2015 - set additional group 27 (sudo)
Sun Oct  4 09:37:53 2015 - setuid() to 102
Sun Oct  4 09:37:53 2015 - your processes number limit is 62225
Sun Oct  4 09:37:53 2015 - your memory page size is 4096 bytes
Sun Oct  4 09:37:53 2015 - detected max file descriptor number: 1024
Sun Oct  4 09:37:53 2015 - lock engine: pthread robust mutexes
Sun Oct  4 09:37:53 2015 - thunder lock: disabled (you can enable it with --thunder-lock)
Sun Oct  4 09:37:53 2015 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/storekeeper/socket fd 3
Sun Oct  4 09:37:53 2015 - Python version: 3.4.3 (default, Jul 28 2015, 18:24:08)  [GCC 4.8.4]
Sun Oct  4 09:37:53 2015 - Set PythonHome to /usr/local/storekeeper/server/flask
Sun Oct  4 09:37:53 2015 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Sun Oct  4 09:37:53 2015 - Python main interpreter initialized at 0x260fdd0
Sun Oct  4 09:37:53 2015 - your server socket listen backlog is limited to 100 connections
Sun Oct  4 09:37:53 2015 - your mercy for graceful operations on workers is 60 seconds
Sun Oct  4 09:37:53 2015 - mapped 363960 bytes (355 KB) for 4 cores
Sun Oct  4 09:37:53 2015 - *** Operational MODE: preforking ***
Sun Oct  4 09:37:53 2015 - added /usr/local/storekeeper/server/ to pythonpath.
Traceback (most recent call last):
  File "/usr/local/storekeeper/server/run.py", line 2, in <module>
    from app.server import app
  File "/usr/local/storekeeper/server/app/server.py", line 11, in <module>
    config = get_config()
  File "/usr/local/storekeeper/server/app/config.py", line 15, in get_config
    config = __translate_primitives(__get_config())
  File "/usr/local/storekeeper/server/app/config.py", line 24, in __get_config
    return config_reader.read()
  File "/usr/local/storekeeper/server/app/modules/yaml_config.py", line 54, in read
    raw_config = config_reader(self.__yaml_config_path)
  File "/usr/local/storekeeper/server/app/modules/yaml_config.py", line 71, in __read_file
    raw_config = fd.read()
  File "/usr/local/storekeeper/server/flask/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 120: ordinal not in range(128)
Sun Oct  4 09:37:53 2015 - unable to load app 0 (mountpoint='') (callable not found or import error)
Sun Oct  4 09:37:53 2015 - *** no app loaded. going in full dynamic mode ***
Sun Oct  4 09:37:53 2015 - spawned uWSGI master process (pid: 24369)
Sun Oct  4 09:37:53 2015 - spawned uWSGI worker 1 (pid: 24377, cores: 1)
Sun Oct  4 09:37:53 2015 - spawned uWSGI worker 2 (pid: 24378, cores: 1)
Sun Oct  4 09:37:53 2015 - spawned uWSGI worker 3 (pid: 24379, cores: 1)
Sun Oct  4 09:37:53 2015 - spawned uWSGI worker 4 (pid: 24380, cores: 1)
```

**Comment by andras-tim** [comment]
There has not been set locales in chroot.

```
LANG="en_US.UTF-8"
LANGUAGE="en_US:en"

locale-gen
```
